### ISSUE TITLE
Request for .ioc File:

### ISSUE THREAD

**Issue by zhangyy103** [BasicCode/ILI9488-STM32#1]
Hi, I'm a beginner and not very familiar with the configuration process in CubeMX. Could you share your CubeMX-generated .ioc file? Although it might not match my chip model exactly, it will serve as a great reference and be very helpful to me. Thank you for your sharing!

**Comment by BasicCode** [comment]
Hi. I don't include .IOC files because they are specific to the microcontroller, project design, and version of CubeMX, and I want the projects to remain as general as possible. Also, ST have pretty good documentation overall, including [how to configure SPI in CubeMX](https://wiki.st.com/stm32mcu/index.php?title=Getting_started_with_SPI&stableid=53151).
